### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by anneiric** [icoderharshit/Checkout#3]
I would be happy to make some minor changes in the style such as the colours of the buttons or the margins to make it more professional.

**Comment by icoderharshit** [comment]
@anneiric I would love to assign you this issue, but due to some reasons I'm pushing this repository into private/archive category. So, I suggest you to create the same issue here 
https://ieiciet.github.io/Checkout-ShoppingCart
and I'll assign you there.
## Happy HacktoberFest '21
